# Generated by Django 3.2 on 2021-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_diaristas_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaristas',
            name='numero',
            field=models.IntegerField(max_length=11),
        ),
    ]
