# Generated by Django 3.2 on 2021-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diaristas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaristas',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='diaristas',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
