# Generated by Django 3.2 on 2021-06-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210626_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaristas',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
